/**
 * File Buzzwords.h
 *
 * @author Edward Pfremmer <epfremme@nerdery.com>
 */

#ifndef ISSUE_37C_BUZZWORDS_H
#define ISSUE_37C_BUZZWORDS_H

#include <string>
#include <vector>

/**
 * Constant buzzwords
 *
 * @constant
 * @type string[]
 */
const std::vector<std::string> BUZZWORDS {
        // general conversation
        "Alignment",
        "At the end of the day",
        "Break through the clutter",
        "Bring to the table",
        "Buzzword",
        "Clear goal",
        "Disruptive innovation",
        "Diversity",
        "Empowerment",
        "Exit strategy",
        "Face time",
        "Generation X",
        "Globalization",
        "Going forward",
        "Grow",
        "Headlights",
        "Holistic approach",
        "Impact",
        "Leverage",
        "Millennial",
        "Moving forward",
        "New normal",
        "On the runway",
        "Organic growth",
        "Outside the box",
        "Paradigm",
        "Paradigm shift",
        "Proactive",
        "Push the envelope",
        "Reach out",
        "Sea change",
        "Sisterhood",
        "Spin up",
        "Spin-up",
        "Strategic Communication",
        "Streamline",
        "Survival strategy",
        "Sustainability",
        "Synergy",
        "Unpack",
        "Wellness",
        "Wheelhouse",
        "Win win",
        "Win-win",

        // education
        "Accountable talk",
        "Higher order thinking",
        "Higher-order thinking",
        "Invested in",
        "Run like a business",
        "Student engagement",
        "Common Core",
        "Bloom's Taxonomy",
        "Differentiated instruction",
        "Digital Literacy",
        "Flipped Classroom",
        "Guided Reading",
        "Instructional Scaffolding",
        "Multiple Intelligences",
        "Project Based Learning",
        "Project-Based Learning",
        "Adaptive Learning",
        "Brain Break",
        "Cooperative Learning",

        // business, sales, and marketing
        "Analytics",
        "Ballpark figure",
        "Bandwidth",
        "Business to Business",
        "Business-to-Business",
        "Business to Consumer",
        "Business-to-Consumer",
        "Best of Breed",
        "Best practices",
        "Bizmeth",
        "Brand",
        "Brick and mortar",
        "Brick-and-mortar",
        "Business process outsourcing",
        "Buzzword compliant",
        "Building Capabilities",
        "Circle Back",
        "Client centric",
        "Client-centric",
        "Cloud computing",
        "Close the loop",
        "Co-opetition",
        "Come to Jesus moment",
        "Content marketing",
        "Core competency",
        "Creative ",
        "Customer-centric",
        "Deep dive",
        "Downsizing",
        "Drinking the Kool-Aid",
        "Early stage",
        "Employer Branding",
        "Eating your own dogfood",
        "Enable",
        "Entitlement",
        "Enterprise",
        "Event horizon",
        "Eyeballs",
        "-free",
        "Free value",
        "Fulfilment issues",
        "Generation Y",
        "Granular",
        "Herding cats",
        "Holistic",
        "Home",
        "Hyperlocal",
        "Innovation",
        "Innovative",
        "Knowledge Process Outsourcing",
        "Leverage",
        "Like cunts",
        "Logistics",
        "Long Tail",
        "Low Hanging Fruit",
        "Make it pop",
        "Mindshare",
        "Mission Critical",
        "Management Visibility",
        "New economy",
        "Next generation",
        "Offshoring",
        "Pain point",
        "Paralysis by Analysis",
        "Part of our DNA",
        "Passionate",
        "Peel back the onion",
        "Pick and Shovel Work",
        "Profit center",
        "Quick win",
        "Return on Investment",
        "Reverse fulfilment",
        "Rightshoring",
        "Seamless",
        "Serum",
        "Share options",
        "Short Runway",
        "Silo",
        "Social Currency",
        "Socialize",
        "Solution",
        "SOX",
        "Sustainability",
        "Storytelling",
        "Startup",
        "Strategy",
        "Synergy",
        "Talent Relationship Management",
        "Tee off",
        "Touch Base",
        "Touchpoint",
        "Upselling",
        "Upcycling",
        "Value added",
        "Value-added",
        "Visibility",

        // science and technology
        "4G",
        "Aggregator",
        "Agile",
        "Ajax",
        "Algorithm",
        "Benchmarking",
        "Back end",
        "Back-end",
        "Beta",
        "Big data",
        "Bleeding edge",
        "Blog",
        "Bring your own Device",
        "Bricks and clicks",
        "Bricks-and-clicks",
        "Clickthrough",
        "Cloud",
        "Collaboration",
        "Content management",
        "CMS",
        "Content Management System",
        "Convergence",
        "Cross platform",
        "Cross-platform",
        "Datafication",
        "Data mining",
        "Data science",
        "Deep dive",
        "Deep web",
        "Design pattern",
        "DevOps",
        "Digital divide",
        "Digital Remastering",
        "DRM",
        "Digital Rights Management",
        "Digital signage",
        "Disruptive Technologies",
        "Document management",
        "Dot bomb",
        "Dot-bomb",
        "E learning",
        "E-learning",
        "Engine",
        "ECM",
        "Enterprise Content Management",
        "ESB",
        "Enterprise Service Bus",
        "Framework",
        "Folksonomy",
        "Fuzzy logic",
        "Graham logic",
        "HTML5",
        "Immersion",
        "Information highway",
        "Information superhighway",
        "Internet of Things",
        "Innovation",
        "Mashup",
        "Mobile",
        "Modularity",

        // politics and current affairs
        "Big society",
        "Information society",
        "Political capital",
        "Statist",
        "Stakeholder",

        // other/uncategorized
        "Antifragile",
        "Best in class"
};

#endif //ISSUE_37C_BUZZWORDS_H
